/**
 * 비즈보드 — 바로가기·로그인 기본 설정 (24개)
 * ID/PW는 설정에서 수정 → 이 기기 localStorage에만 저장.
 * 실제 계정은 Git에 커밋하지 마세요.
 */
window.BIZ_BOARD_DEFAULTS = {
  version: "1.0.0",
  appName: "비즈보드",
  shortcuts: [
    {
      id: "themango",
      name: "더망고",
      group: "수집",
      color: "#1B7A4E",
      loginUrl: "https://www.themango.co.kr/member/login.php",
      homeUrl: "https://www.themango.co.kr/",
      loginMethod: "form_post",
      formAction: "https://www.themango.co.kr/bbs/login_check.php",
      formMethod: "POST",
      userField: "mb_id",
      passField: "mb_password",
      username: "",
      password: "",
    },
    {
      id: "naver",
      name: "네이버",
      group: "포털",
      color: "#03C75A",
      loginUrl: "https://nid.naver.com/nidlogin.login",
      homeUrl: "https://www.naver.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "naver-smartstore",
      name: "스마트스토어",
      group: "판매",
      color: "#00C73C",
      loginUrl: "https://sell.smartstore.naver.com/",
      homeUrl: "https://sell.smartstore.naver.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "coupang-wing",
      name: "쿠팡윙",
      group: "판매",
      color: "#E94235",
      loginUrl: "https://wing.coupang.com/",
      homeUrl: "https://wing.coupang.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "domeggook",
      name: "도매꾹",
      group: "도매",
      color: "#F15A22",
      loginUrl: "https://domeggook.com/main/member/member_login.php",
      homeUrl: "https://domeggook.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "domeme",
      name: "도매매",
      group: "도매",
      color: "#FF6B00",
      loginUrl: "https://domeme.com/",
      homeUrl: "https://domeme.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "elevenst",
      name: "11번가",
      group: "판매",
      color: "#FF0038",
      loginUrl: "https://login.11st.co.kr/",
      homeUrl: "https://soffice.11st.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "gmarket",
      name: "G마켓",
      group: "판매",
      color: "#00D660",
      loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
      homeUrl: "https://www.gmarket.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "auction",
      name: "옥션",
      group: "판매",
      color: "#E4002B",
      loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
      homeUrl: "https://www.auction.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "esmplus",
      name: "ESM Plus",
      group: "판매",
      color: "#2B2B2B",
      loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
      homeUrl: "https://www.esmplus.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "cafe24",
      name: "카페24",
      group: "쇼핑몰",
      color: "#1A73E8",
      loginUrl: "https://user.cafe24.com/",
      homeUrl: "https://www.cafe24.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "makeshop",
      name: "메이크샵",
      group: "쇼핑몰",
      color: "#5B2C91",
      loginUrl: "https://www.makeshop.co.kr/",
      homeUrl: "https://www.makeshop.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "sabangnet",
      name: "사방넷",
      group: "연동",
      color: "#0E7490",
      loginUrl: "https://www.sabangnet.co.kr/",
      homeUrl: "https://www.sabangnet.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "playauto",
      name: "플레이오토",
      group: "연동",
      color: "#2563EB",
      loginUrl: "https://www.playauto.co.kr/",
      homeUrl: "https://www.playauto.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "sellmate",
      name: "셀메이트",
      group: "연동",
      color: "#0F766E",
      loginUrl: "https://www.sellmate.co.kr/",
      homeUrl: "https://www.sellmate.co.kr/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "itemscout",
      name: "아이템스카우트",
      group: "분석",
      color: "#4F46E5",
      loginUrl: "https://itemscout.io/",
      homeUrl: "https://itemscout.io/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "alibaba",
      name: "Alibaba",
      group: "해외",
      color: "#FF6A00",
      loginUrl: "https://login.alibaba.com/",
      homeUrl: "https://www.alibaba.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "1688",
      name: "1688",
      group: "해외",
      color: "#FF4000",
      loginUrl: "https://login.taobao.com/",
      homeUrl: "https://www.1688.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "taobao",
      name: "타오바오",
      group: "해외",
      color: "#FF5000",
      loginUrl: "https://login.taobao.com/",
      homeUrl: "https://world.taobao.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "kakao-biz",
      name: "카카오비즈",
      group: "마케팅",
      color: "#FEE500",
      textColor: "#191600",
      loginUrl: "https://business.kakao.com/",
      homeUrl: "https://business.kakao.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "google",
      name: "Google",
      group: "포털",
      color: "#4285F4",
      loginUrl: "https://accounts.google.com/",
      homeUrl: "https://www.google.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "github",
      name: "GitHub",
      group: "개발",
      color: "#24292F",
      loginUrl: "https://github.com/login",
      homeUrl: "https://github.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "notion",
      name: "Notion",
      group: "업무",
      color: "#111111",
      loginUrl: "https://www.notion.so/login",
      homeUrl: "https://www.notion.so/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
    {
      id: "slack",
      name: "Slack",
      group: "업무",
      color: "#4A154B",
      loginUrl: "https://slack.com/signin",
      homeUrl: "https://slack.com/",
      loginMethod: "assist",
      username: "",
      password: "",
    },
  ],
};
