/**
 * 비즈보드 — 바로가기 사이트 정의 (20개 이상)
 * id/pw 기본값은 아래에서 사전 정의. 설정 화면·localStorage로 덮어쓸 수 있음.
 *
 * auth:
 *   - post  : loginUrl 로 hidden form POST (자동 로그인)
 *   - get   : loginUrl?idField=…&pwField=… 로 이동
 *   - open  : 로그인 URL 연 뒤 ID/PW 자동복사·붙여넣기 보조
 */
window.BIZ_BOARD_SITES = [
  {
    id: "tmg-admin",
    name: "더망고 관리자",
    group: "수집",
    color: "#0f766e",
    url: "https://tmg1898.cafe24.com/mall/admin/admin.php",
    loginUrl: "https://tmg1898.cafe24.com/mall/m_login_ok.php",
    loginPage: "https://tmg1898.cafe24.com/mall/admin/admin_login.php",
    auth: "post",
    idField: "login_id",
    pwField: "login_pass",
    extraFields: {
      ps_ssl: "",
      ps_murl: "https://tmg1898.cafe24.com//m_login_ok.php",
      ps_mode2: "login",
      url: "./admin/admin.php",
      recaptcha_token: "",
    },
    userId: "",
    password: "",
  },
  {
    id: "tmg-bulk",
    name: "더망고 대량수집",
    group: "수집",
    color: "#0d9488",
    url: "https://tmg1898.cafe24.com/mall/admin/shop/getGoodsNew.php",
    loginUrl: "https://tmg1898.cafe24.com/mall/m_login_ok.php",
    loginPage: "https://tmg1898.cafe24.com/mall/admin/admin_login.php",
    auth: "post",
    idField: "login_id",
    pwField: "login_pass",
    extraFields: {
      ps_ssl: "",
      ps_murl: "https://tmg1898.cafe24.com//m_login_ok.php",
      ps_mode2: "login",
      url: "./admin/shop/getGoodsNew.php",
      recaptcha_token: "",
    },
    userId: "",
    password: "",
  },
  {
    id: "cafe24",
    name: "Cafe24 관리자",
    group: "쇼핑몰",
    color: "#0369a1",
    url: "https://eclogin.cafe24.com/Shop/",
    loginUrl: "https://eclogin.cafe24.com/Shop/",
    auth: "open",
    idField: "loginId",
    pwField: "loginPasswd",
    userId: "",
    password: "",
  },
  {
    id: "smartstore",
    name: "스마트스토어센터",
    group: "쇼핑몰",
    color: "#15803d",
    url: "https://sell.smartstore.naver.com/",
    loginUrl: "https://sell.smartstore.naver.com/#/login",
    auth: "open",
    idField: "id",
    pwField: "pw",
    userId: "",
    password: "",
  },
  {
    id: "coupang-wing",
    name: "쿠팡 윙",
    group: "쇼핑몰",
    color: "#c2410c",
    url: "https://wing.coupang.com/",
    loginUrl: "https://wing.coupang.com/login",
    auth: "open",
    idField: "username",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "11st-seller",
    name: "11번가 셀러",
    group: "쇼핑몰",
    color: "#be123c",
    url: "https://soffice.11st.co.kr/",
    loginUrl: "https://soffice.11st.co.kr/",
    auth: "open",
    idField: "loginName",
    pwField: "passWord",
    userId: "",
    password: "",
  },
  {
    id: "gmarket",
    name: "G마켓 판매자",
    group: "쇼핑몰",
    color: "#1d4ed8",
    url: "https://www.esmplus.com/",
    loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
    auth: "open",
    idField: "Id",
    pwField: "Password",
    userId: "",
    password: "",
  },
  {
    id: "auction",
    name: "옥션 판매자",
    group: "쇼핑몰",
    color: "#7c2d12",
    url: "https://www.esmplus.com/",
    loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
    auth: "open",
    idField: "Id",
    pwField: "Password",
    userId: "",
    password: "",
  },
  {
    id: "kakao-store",
    name: "카카오톡 스토어",
    group: "쇼핑몰",
    color: "#a16207",
    url: "https://shopping-seller.kakao.com/",
    loginUrl: "https://shopping-seller.kakao.com/",
    auth: "open",
    idField: "email",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "zigzag",
    name: "지그재그 파트너",
    group: "패션",
    color: "#9d174d",
    url: "https://partners.zigzag.kr/",
    loginUrl: "https://partners.zigzag.kr/",
    auth: "open",
    idField: "email",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "ably",
    name: "에이블리 파트너",
    group: "패션",
    color: "#86198f",
    url: "https://cafe.a-bly.com/",
    loginUrl: "https://cafe.a-bly.com/",
    auth: "open",
    idField: "email",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "musinsa",
    name: "무신사 파트너",
    group: "패션",
    color: "#111827",
    url: "https://partner.musinsa.com/",
    loginUrl: "https://partner.musinsa.com/",
    auth: "open",
    idField: "username",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "itemscout",
    name: "아이템스카우트",
    group: "분석",
    color: "#1e40af",
    url: "https://itemscout.io/",
    loginUrl: "https://itemscout.io/login",
    auth: "open",
    idField: "email",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "sellerhub",
    name: "셀러허브",
    group: "분석",
    color: "#065f46",
    url: "https://www.sellerhub.co.kr/",
    loginUrl: "https://www.sellerhub.co.kr/",
    auth: "open",
    idField: "user_id",
    pwField: "user_pw",
    userId: "",
    password: "",
  },
  {
    id: "sabangnet",
    name: "사방넷",
    group: "연동",
    color: "#1e3a8a",
    url: "https://www.sabangnet.co.kr/",
    loginUrl: "https://www.sabangnet.co.kr/",
    auth: "open",
    idField: "id",
    pwField: "passwd",
    userId: "",
    password: "",
  },
  {
    id: "playauto",
    name: "플레이오토",
    group: "연동",
    color: "#3730a3",
    url: "https://www.playauto.co.kr/",
    loginUrl: "https://www.playauto.co.kr/",
    auth: "open",
    idField: "userid",
    pwField: "passwd",
    userId: "",
    password: "",
  },
  {
    id: "esmplus",
    name: "ESMplus",
    group: "연동",
    color: "#1e40af",
    url: "https://www.esmplus.com/",
    loginUrl: "https://www.esmplus.com/Member/SignIn/LogOn",
    auth: "open",
    idField: "Id",
    pwField: "Password",
    userId: "",
    password: "",
  },
  {
    id: "naver-ads",
    name: "네이버 검색광고",
    group: "광고",
    color: "#166534",
    url: "https://searchad.naver.com/",
    loginUrl: "https://searchad.naver.com/",
    auth: "open",
    idField: "id",
    pwField: "pw",
    userId: "",
    password: "",
  },
  {
    id: "kakao-moment",
    name: "카카오 모먼트",
    group: "광고",
    color: "#854d0e",
    url: "https://moment.kakao.com/",
    loginUrl: "https://moment.kakao.com/",
    auth: "open",
    idField: "email",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "google-ads",
    name: "구글 애즈",
    group: "광고",
    color: "#b45309",
    url: "https://ads.google.com/",
    loginUrl: "https://ads.google.com/",
    auth: "open",
    idField: "Email",
    pwField: "Passwd",
    userId: "",
    password: "",
  },
  {
    id: "meta-ads",
    name: "메타 광고관리자",
    group: "광고",
    color: "#1d4ed8",
    url: "https://business.facebook.com/",
    loginUrl: "https://business.facebook.com/",
    auth: "open",
    idField: "email",
    pwField: "pass",
    userId: "",
    password: "",
  },
  {
    id: "cj-logistics",
    name: "CJ대한통운",
    group: "물류",
    color: "#b91c1c",
    url: "https://www.cjlogistics.com/",
    loginUrl: "https://www.cjlogistics.com/",
    auth: "open",
    idField: "id",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "hometax",
    name: "홈택스",
    group: "행정",
    color: "#1e3a5f",
    url: "https://hometax.go.kr/",
    loginUrl: "https://hometax.go.kr/",
    auth: "open",
    idField: "id",
    pwField: "password",
    userId: "",
    password: "",
  },
  {
    id: "naver-commerce",
    name: "네이버 커머스",
    group: "분석",
    color: "#14532d",
    url: "https://sell.smartstore.naver.com/#/home/dashboard",
    loginUrl: "https://sell.smartstore.naver.com/#/login",
    auth: "open",
    idField: "id",
    pwField: "pw",
    userId: "",
    password: "",
  },
];
